sudo: false
language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6.4.0"
git:
  quiet: true
  depth: 1
notifications:
  email: false
cache:
  directories:
    - ~/.npm
env:
  - NODE_ENV=development
before_install:
  - nvm install-latest-npm
install:
  - npm install
